/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mymusic;
import javax.swing.JOptionPane;


/**
 *
 * @author niamh
 */
public class AddGUI extends javax.swing.JFrame {

    StackInterface likedStack = new SongStack();
    LinearInterface popL = new DoubleList();
    LinearInterface soundL = new DoubleList();
    LinearInterface repeatL = new DoubleList();
    
    /**
     * Creates new form MusicGUI
     */
    public AddGUI() {
        initComponents();
        addBTN.setVisible(false);
        deleteBTN.setVisible(false);
        moveBTN.setVisible(false);
        genreLBL.setVisible(false);
        moveBTN.setVisible(false);
        nameLBL.setVisible(false);
        popRBTN.setVisible(false);
        returnBTN.setVisible(false);
        searchBTN.setVisible(false);
        soundRBTN.setVisible(false);
        nameTF.setVisible(false);
        repeatBTN.setVisible(false);
        repeatDisplayTF.setVisible(false);
        
        likeLBTN.setVisible(false);
        popLBTN.setVisible(false);
        soundLBTN.setVisible(false);
        veiwRetBTN.setVisible(false);
        likedDisplayTF.setVisible(false);
        popDisplayTF.setVisible(false);
        soundDisplayTF.setVisible(false);
        
        editBTN.setVisible(true);
        viewBTN.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genreBTNGroup = new javax.swing.ButtonGroup();
        tilteLB = new javax.swing.JLabel();
        addBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        genreLBL = new javax.swing.JLabel();
        nameLBL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        popRBTN = new javax.swing.JRadioButton();
        soundRBTN = new javax.swing.JRadioButton();
        searchBTN = new javax.swing.JButton();
        returnBTN = new javax.swing.JButton();
        repeatBTN = new javax.swing.JButton();
        repeatDisplayTF = new javax.swing.JTextField();
        popDisplayTF = new javax.swing.JTextField();
        moveBTN = new javax.swing.JButton();
        soundDisplayTF = new javax.swing.JTextField();
        editBTN = new javax.swing.JButton();
        viewBTN = new javax.swing.JButton();
        likeLBTN = new javax.swing.JButton();
        soundLBTN = new javax.swing.JButton();
        popLBTN = new javax.swing.JButton();
        veiwRetBTN = new javax.swing.JButton();
        likedDisplayTF = new javax.swing.JTextField();
        bgLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(370, 545));
        setPreferredSize(new java.awt.Dimension(370, 545));
        getContentPane().setLayout(null);

        tilteLB.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tilteLB.setText("My Music");
        getContentPane().add(tilteLB);
        tilteLB.setBounds(90, 110, 170, 70);

        addBTN.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });
        getContentPane().add(addBTN);
        addBTN.setBounds(90, 280, 80, 30);

        deleteBTN.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBTN);
        deleteBTN.setBounds(180, 280, 80, 30);

        genreLBL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        genreLBL.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        genreLBL.setText("Genre: ");
        getContentPane().add(genreLBL);
        genreLBL.setBounds(80, 230, 110, 22);

        nameLBL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        nameLBL.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        nameLBL.setText("Song Name: ");
        getContentPane().add(nameLBL);
        nameLBL.setBounds(90, 200, 100, 22);

        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });
        getContentPane().add(nameTF);
        nameTF.setBounds(190, 200, 71, 22);

        genreBTNGroup.add(popRBTN);
        popRBTN.setText("Pop Music");
        popRBTN.setToolTipText("");
        getContentPane().add(popRBTN);
        popRBTN.setBounds(190, 250, 98, 21);

        genreBTNGroup.add(soundRBTN);
        soundRBTN.setText("Soundtracks");
        soundRBTN.setToolTipText("");
        getContentPane().add(soundRBTN);
        soundRBTN.setBounds(190, 230, 110, 21);

        searchBTN.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });
        getContentPane().add(searchBTN);
        searchBTN.setBounds(90, 320, 80, 30);

        returnBTN.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        returnBTN.setText("Return");
        returnBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBTNActionPerformed(evt);
            }
        });
        getContentPane().add(returnBTN);
        returnBTN.setBounds(130, 440, 90, 30);

        repeatBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        repeatBTN.setText("Repeat");
        repeatBTN.setMaximumSize(new java.awt.Dimension(97, 45));
        repeatBTN.setMinimumSize(new java.awt.Dimension(97, 45));
        repeatBTN.setPreferredSize(new java.awt.Dimension(97, 45));
        repeatBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repeatBTNActionPerformed(evt);
            }
        });
        getContentPane().add(repeatBTN);
        repeatBTN.setBounds(90, 370, 170, 30);
        getContentPane().add(repeatDisplayTF);
        repeatDisplayTF.setBounds(110, 400, 130, 30);
        getContentPane().add(popDisplayTF);
        popDisplayTF.setBounds(110, 360, 130, 30);

        moveBTN.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        moveBTN.setText("Move to");
        moveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveBTNActionPerformed(evt);
            }
        });
        getContentPane().add(moveBTN);
        moveBTN.setBounds(180, 320, 80, 30);

        soundDisplayTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundDisplayTFActionPerformed(evt);
            }
        });
        getContentPane().add(soundDisplayTF);
        soundDisplayTF.setBounds(110, 280, 130, 30);

        editBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editBTN.setText("Edit Songs");
        editBTN.setMaximumSize(new java.awt.Dimension(97, 45));
        editBTN.setMinimumSize(new java.awt.Dimension(97, 45));
        editBTN.setPreferredSize(new java.awt.Dimension(97, 45));
        editBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTNActionPerformed(evt);
            }
        });
        getContentPane().add(editBTN);
        editBTN.setBounds(110, 230, 120, 40);

        viewBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        viewBTN.setText("View Playlists");
        viewBTN.setMaximumSize(new java.awt.Dimension(97, 45));
        viewBTN.setMinimumSize(new java.awt.Dimension(97, 45));
        viewBTN.setPreferredSize(new java.awt.Dimension(97, 45));
        viewBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBTNActionPerformed(evt);
            }
        });
        getContentPane().add(viewBTN);
        viewBTN.setBounds(110, 280, 120, 40);

        likeLBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        likeLBTN.setText("Liked Songs");
        likeLBTN.setMaximumSize(new java.awt.Dimension(97, 45));
        likeLBTN.setMinimumSize(new java.awt.Dimension(97, 45));
        likeLBTN.setPreferredSize(new java.awt.Dimension(97, 45));
        likeLBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likeLBTNActionPerformed(evt);
            }
        });
        getContentPane().add(likeLBTN);
        likeLBTN.setBounds(90, 180, 170, 30);

        soundLBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        soundLBTN.setText("Soundtracks");
        soundLBTN.setMaximumSize(new java.awt.Dimension(97, 45));
        soundLBTN.setMinimumSize(new java.awt.Dimension(97, 45));
        soundLBTN.setPreferredSize(new java.awt.Dimension(97, 45));
        soundLBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundLBTNActionPerformed(evt);
            }
        });
        getContentPane().add(soundLBTN);
        soundLBTN.setBounds(90, 250, 170, 30);

        popLBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        popLBTN.setText("Pop Music");
        popLBTN.setMaximumSize(new java.awt.Dimension(97, 45));
        popLBTN.setMinimumSize(new java.awt.Dimension(97, 45));
        popLBTN.setPreferredSize(new java.awt.Dimension(97, 45));
        popLBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popLBTNActionPerformed(evt);
            }
        });
        getContentPane().add(popLBTN);
        popLBTN.setBounds(90, 330, 170, 30);

        veiwRetBTN.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        veiwRetBTN.setText("Return");
        veiwRetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiwRetBTNActionPerformed(evt);
            }
        });
        getContentPane().add(veiwRetBTN);
        veiwRetBTN.setBounds(130, 470, 90, 30);
        getContentPane().add(likedDisplayTF);
        likedDisplayTF.setBounds(110, 210, 130, 30);

        bgLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymusic/musics.png"))); // NOI18N
        getContentPane().add(bgLB);
        bgLB.setBounds(0, 0, 360, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void add(String name, LinearInterface playlist){
        if(!search(name, playlist)){
            likedStack.push(name);
            playlist.add(1, name);
        }
        else{
            System.out.println("Already in playlist");
        }
    }
    
    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // add song to liked playlist and selected genre
        String name = nameTF.getText();
        if(soundRBTN.isSelected()){
            add(name, soundL);
        }
        else if(popRBTN.isSelected()){
            add(name,popL);
        }
        else{
            System.out.println("Pick genre:");
        }
        
        JOptionPane.showMessageDialog(null, "Song entered successfully");
        nameTF.setText("");
        
    }//GEN-LAST:event_addBTNActionPerformed
    private void delete(String name, LinearInterface playlist){
        if(search(name, playlist)){
            //for deleting in playlist DLL
            for(int j = 0; j<(playlist.size()); j++){
                if(playlist.getItem(j).contains(name)){
                        playlist.remove(j);
                        break;
                    }
                }
               
            // Deleting for liked list
            likedStack.pop();
        }
        else{
            System.out.println("Not in the list");
        }
        
        
    }
    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        String name = nameTF.getText();
        
        if(soundRBTN.isSelected()){
            delete(name, soundL);
        }
        else if(popRBTN.isSelected()){
            delete(name, popL);
        }
               
        JOptionPane.showMessageDialog(null, "Song deleted successfully");
        nameTF.setText("");
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed
    
    private boolean search(String name, LinearInterface playlist){
        // Search list
        boolean visi = false;
        
        //for searching in playlist DLL
            for(int j = 0; j<playlist.size(); j++){
               if(playlist.getItem(j).contains(name)){
                    visi = true;
                    break;
                }
                else{
                    visi = false;
                } 
            }
        
        return visi;
    }
    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        String name = nameTF.getText();
        if(soundRBTN.isSelected()){
            System.out.println(search(name, soundL));
        }
        else if(popRBTN.isSelected()){
            System.out.println(search(name, popL));
        }
        else{
            JOptionPane.showMessageDialog(null, "Choose a genre");
        }
        JOptionPane.showMessageDialog(null, "Song entered successfully");
        nameTF.setText("");
        
    }//GEN-LAST:event_searchBTNActionPerformed
    
    private void move(String name, LinearInterface playlist, LinearInterface orgPlaylist){
        if(search(name, orgPlaylist)){
            delete(name, orgPlaylist);
            add(name, playlist);
        }
        else{
            JOptionPane.showMessageDialog(null, "Song not in playlist");
        }
    }
    
    private void moveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveBTNActionPerformed
        // Move:
        String name = nameTF.getText();
        if(soundRBTN.isSelected()){
            move(name, soundL, popL);
        }
        else if(popRBTN.isSelected()){
            move(name, popL, soundL);
        }
        else{
            JOptionPane.showMessageDialog(null, "Choose a genre");
        }
        
        JOptionPane.showMessageDialog(null, "Song entered successfully");
        nameTF.setText("");
        
    }//GEN-LAST:event_moveBTNActionPerformed

    private void returnBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBTNActionPerformed
        // Return to home/music gui:
        addBTN.setVisible(false);
        deleteBTN.setVisible(false);
        moveBTN.setVisible(false);
        genreLBL.setVisible(false);
        moveBTN.setVisible(false);
        nameLBL.setVisible(false);
        popRBTN.setVisible(false);
        returnBTN.setVisible(false);
        searchBTN.setVisible(false);
        soundRBTN.setVisible(false);
        nameTF.setVisible(false);
        repeatBTN.setVisible(false);
        repeatDisplayTF.setVisible(false);
        
        likeLBTN.setVisible(false);
        popLBTN.setVisible(false);
        soundLBTN.setVisible(false);
        veiwRetBTN.setVisible(false);
        likedDisplayTF.setVisible(false);
        popDisplayTF.setVisible(false);
        soundDisplayTF.setVisible(false);
        
        editBTN.setVisible(true);
        viewBTN.setVisible(true);
    }//GEN-LAST:event_returnBTNActionPerformed

    private void editBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTNActionPerformed
        addBTN.setVisible(true);
        deleteBTN.setVisible(true);
        moveBTN.setVisible(true);
        genreLBL.setVisible(true);
        moveBTN.setVisible(true);
        nameLBL.setVisible(true);
        popRBTN.setVisible(true);
        returnBTN.setVisible(true);
        searchBTN.setVisible(true);
        soundRBTN.setVisible(true);
        nameTF.setVisible(true);
        repeatBTN.setVisible(true);
        repeatDisplayTF.setVisible(true);
        
        likeLBTN.setVisible(false);
        popLBTN.setVisible(false);
        soundLBTN.setVisible(false);
        veiwRetBTN.setVisible(false);
        likedDisplayTF.setVisible(false);
        popDisplayTF.setVisible(false);
        soundDisplayTF.setVisible(false);
        
        editBTN.setVisible(false);
        viewBTN.setVisible(false);
    }//GEN-LAST:event_editBTNActionPerformed

    private void viewBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBTNActionPerformed
        addBTN.setVisible(false);
        deleteBTN.setVisible(false);
        moveBTN.setVisible(false);
        genreLBL.setVisible(false);
        moveBTN.setVisible(false);
        nameLBL.setVisible(false);
        popRBTN.setVisible(false);
        returnBTN.setVisible(false);
        searchBTN.setVisible(false);
        soundRBTN.setVisible(false);
        nameTF.setVisible(false);
        repeatBTN.setVisible(false);
        repeatDisplayTF.setVisible(false);
        
        likeLBTN.setVisible(true);
        popLBTN.setVisible(true);
        soundLBTN.setVisible(true);
        veiwRetBTN.setVisible(true);
        likedDisplayTF.setVisible(true);
        popDisplayTF.setVisible(true);
        soundDisplayTF.setVisible(true);
        
        editBTN.setVisible(false);
        viewBTN.setVisible(false);
    }//GEN-LAST:event_viewBTNActionPerformed

    private void likeLBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likeLBTNActionPerformed
        // Display Liked Songs
        likedDisplayTF.setText(likedStack.display() + likedStack.size());
    }//GEN-LAST:event_likeLBTNActionPerformed

    private void soundLBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundLBTNActionPerformed
        // Display Soundtrack playlist:
        soundDisplayTF.setText(soundL.printList() + soundL.size());
    }//GEN-LAST:event_soundLBTNActionPerformed

    private void popLBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popLBTNActionPerformed
        // Display Pop playlist:
        popDisplayTF.setText(popL.printList() + popL.size());
    }//GEN-LAST:event_popLBTNActionPerformed

    private void veiwRetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiwRetBTNActionPerformed
        addBTN.setVisible(false);
        deleteBTN.setVisible(false);
        moveBTN.setVisible(false);
        genreLBL.setVisible(false);
        moveBTN.setVisible(false);
        nameLBL.setVisible(false);
        popRBTN.setVisible(false);
        returnBTN.setVisible(false);
        searchBTN.setVisible(false);
        soundRBTN.setVisible(false);
        nameTF.setVisible(false);
        repeatBTN.setVisible(false);
        repeatDisplayTF.setVisible(false);
        
        likeLBTN.setVisible(false);
        popLBTN.setVisible(false);
        soundLBTN.setVisible(false);
        veiwRetBTN.setVisible(false);
        likedDisplayTF.setVisible(false);
        popDisplayTF.setVisible(false);
        soundDisplayTF.setVisible(false);
        
        editBTN.setVisible(true);
        viewBTN.setVisible(true);
    }//GEN-LAST:event_veiwRetBTNActionPerformed

    private void soundDisplayTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundDisplayTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soundDisplayTFActionPerformed

    private void repeatBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repeatBTNActionPerformed
        // Display repeat:
        if(soundRBTN.isSelected()){
            repeatL.addList(soundL);
            repeatL.addList(soundL);
            repeatL.addList(soundL);
            String list = repeatL.printList();
            repeatDisplayTF.setText("Songs: " + list);
            
        }
        else if(popRBTN.isSelected()){
            repeatL.addList(popL);
            repeatL.addList(popL);
            repeatL.addList(popL);
            String list = popL.printList();
            repeatDisplayTF.setText("Songs: " + list);
            
        }
        else{
         JOptionPane.showMessageDialog(null, "Choose a genre:");
        }
    }//GEN-LAST:event_repeatBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JLabel bgLB;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JButton editBTN;
    private javax.swing.ButtonGroup genreBTNGroup;
    private javax.swing.JLabel genreLBL;
    private javax.swing.JButton likeLBTN;
    private javax.swing.JTextField likedDisplayTF;
    private javax.swing.JButton moveBTN;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField popDisplayTF;
    private javax.swing.JButton popLBTN;
    private javax.swing.JRadioButton popRBTN;
    private javax.swing.JButton repeatBTN;
    private javax.swing.JTextField repeatDisplayTF;
    private javax.swing.JButton returnBTN;
    private javax.swing.JButton searchBTN;
    private javax.swing.JTextField soundDisplayTF;
    private javax.swing.JButton soundLBTN;
    private javax.swing.JRadioButton soundRBTN;
    private javax.swing.JLabel tilteLB;
    private javax.swing.JButton veiwRetBTN;
    private javax.swing.JButton viewBTN;
    // End of variables declaration//GEN-END:variables
}
