/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mymusic;

/**
 * MusicGUI
 * @author niamh
 * 12/03/24
 */
public class MusicGUI extends javax.swing.JFrame {

    /**
     * Creates new form MusicGUI
     */
    public MusicGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        tilteLB = new javax.swing.JLabel();
        viewBTN = new javax.swing.JButton();
        editBTN = new javax.swing.JButton();
        bgLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(370, 545));
        setPreferredSize(new java.awt.Dimension(370, 545));
        getContentPane().setLayout(null);

        tilteLB.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tilteLB.setText("My Music");
        getContentPane().add(tilteLB);
        tilteLB.setBounds(90, 130, 170, 70);

        viewBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        viewBTN.setText("Veiw Playlists");
        viewBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBTNActionPerformed(evt);
            }
        });
        getContentPane().add(viewBTN);
        viewBTN.setBounds(100, 260, 130, 40);

        editBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editBTN.setText("Edit Songs");
        editBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTNActionPerformed(evt);
            }
        });
        getContentPane().add(editBTN);
        editBTN.setBounds(100, 210, 130, 40);

        bgLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymusic/musics.png"))); // NOI18N
        getContentPane().add(bgLB);
        bgLB.setBounds(0, 0, 360, 510);

        pack();
    }// </editor-fold>                        

    private void editBTNActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        AddGUI addsong = new AddGUI();
        addsong.setVisible(true);
        this.dispose();
    }                                       

    private void viewBTNActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        ViewGUI view = new ViewGUI();
        view.setVisible(true);
        this.dispose();
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel bgLB;
    private javax.swing.JButton editBTN;
    private javax.swing.JLabel tilteLB;
    private javax.swing.JButton viewBTN;
    // End of variables declaration                   
}
