/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mymusic;

/**
 *
 * @author niamh
 */
public class ViewGUI extends javax.swing.JFrame {

    /**
     * Creates new form MusicGUI
     */
    public ViewGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        tilteLB = new javax.swing.JLabel();
        returnBTN = new javax.swing.JButton();
        likedBTN = new javax.swing.JButton();
        soundBTN = new javax.swing.JButton();
        popBTN = new javax.swing.JButton();
        playlistLBL = new javax.swing.JLabel();
        bgLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(370, 545));
        setPreferredSize(new java.awt.Dimension(370, 545));
        getContentPane().setLayout(null);

        tilteLB.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tilteLB.setText("My Music");
        getContentPane().add(tilteLB);
        tilteLB.setBounds(90, 130, 170, 70);

        returnBTN.setText("Return");
        returnBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBTNActionPerformed(evt);
            }
        });
        getContentPane().add(returnBTN);
        returnBTN.setBounds(130, 360, 80, 30);

        likedBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        likedBTN.setText("Liked Songs");
        likedBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likedBTNActionPerformed(evt);
            }
        });
        getContentPane().add(likedBTN);
        likedBTN.setBounds(110, 240, 120, 30);

        soundBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        soundBTN.setText("Soundtracks");
        soundBTN.setMaximumSize(new java.awt.Dimension(103, 27));
        soundBTN.setMinimumSize(new java.awt.Dimension(103, 27));
        soundBTN.setPreferredSize(new java.awt.Dimension(103, 27));
        soundBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundBTNActionPerformed(evt);
            }
        });
        getContentPane().add(soundBTN);
        soundBTN.setBounds(110, 280, 120, 30);

        popBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        popBTN.setText("Pop Music");
        popBTN.setMaximumSize(new java.awt.Dimension(103, 27));
        popBTN.setMinimumSize(new java.awt.Dimension(103, 27));
        popBTN.setPreferredSize(new java.awt.Dimension(103, 27));
        popBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popBTNActionPerformed(evt);
            }
        });
        getContentPane().add(popBTN);
        popBTN.setBounds(110, 320, 120, 30);

        playlistLBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        playlistLBL.setText("Playlists:");
        getContentPane().add(playlistLBL);
        playlistLBL.setBounds(140, 200, 80, 30);

        bgLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymusic/musics.png"))); // NOI18N
        getContentPane().add(bgLB);
        bgLB.setBounds(0, 0, 360, 510);

        pack();
    }// </editor-fold>                        

    private void returnBTNActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // Return to home/music gui
        MusicGUI music = new MusicGUI();
        music.setVisible(true);
        this.dispose();
    }                                         

    private void likedBTNActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void soundBTNActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void popBTNActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel bgLB;
    private javax.swing.JButton likedBTN;
    private javax.swing.JLabel playlistLBL;
    private javax.swing.JButton popBTN;
    private javax.swing.JButton returnBTN;
    private javax.swing.JButton soundBTN;
    private javax.swing.JLabel tilteLB;
    // End of variables declaration                   
}
